# model settings
embedding_size: 128
hidden_size: 256
latent_size: 64
rnn_type: "lstm"
num_dec_layers: 2
alpha_aux: 0.4

# training settings
learner: adam
learning_rate: 0.0005
eval_step: 2
stopping_step: 5
dropout_ratio: 0.5
